on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: npm install, npm run coveralls
        run: |
          npm install
          npm run coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@v2
